// import '../imports/api/device/publish.coffee';
import '../imports/api/device/server-methods.js';
import '../imports/api/data/publish.js';
import '../imports/api/environment/publish.js';
import '../imports/api/notifications/publish.js';
import '../imports/api/thing/publish.js';
import '../imports/api/device/methods.js';
import '../imports/api/environment/methods.js';
import '../imports/api/notifications/methods.js';
import '../imports/api/thing/methods.js';